version: '3.1'

services:
    db:
        image: postgres:10.1
        environment:
            POSTGRES_PASSWORD: asdfgh
        ports:
            - "5432:5432"
            # Exposes the PostgreSQL port (5432) so that
            # you may connect to it from the host machine.
            # See github.com/MDooley47/pgweb
        volumes:
            - portal-db:/var/lib/postgresql/data
            - .:/var/www
        restart: always
    zf:
        depends_on:
            - db
        build: .
        ports:
            - "0.0.0.0:80:80"
            - "0.0.0.0:443:443"
        volumes:
            - .:/var/www
            - portal-files:/volumes/storage
            - ./simplesamlphp/cert:/var/www/vendor/simplesamlphp/simplesamlphpcert/
            - ./simplesamlphp/config:/var/www/vendor/simplesamlphp/simplesamlphp/config/
            - ./simplesamlphp/metadata:/var/www/vendor/simplesamlphp/simplesamlphp/metadata
            - ./data/logs:/var/www/vendor/simplesamlphp/simplesamlphp/log
            - ./xdebug/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        links:
            - db
        restart: always
#       migration:
#       build: .
#       command: ["./docker-scripts/wait-for-postgres.sh", "db", "php", "data/load_db.php"]
#       volumes:
#           - .:/var/www
#       depends_on:
#           - db
#           - zf
volumes:
    portal-files:
        external:
            name: portal-ex-data
    portal-db:
        external:
            name: portal-pgdata
