version: '3.1'

services:
    db:
        image: postgres:10.1
        environment:
            POSTGRES_PASSWORD: asdfgh
    zf:
        build: .
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - /var/www/vendor
